#pragma once

#define LWLOG_NO_TIME			0
#define LWLOG_USE_LOCALTIME		0
#define LWLOG_USE_PRECISE_UNITS 0

#define LWLOG_USE_THREAD_ID		0
#define LWLOG_USE_PROCESS_ID	0

#define LWLOG_NO_FORMATTING		0
#define LWLOG_USE_FMT			0
#define LWLOG_USE_STD_FORMAT	0