name: Dynamic Analysis

on:  
  workflow_dispatch:
  workflow_run:
    workflows: ["Linux"]  # Replace with the exact name of your Linux build workflow
    types: [completed]

jobs:
  valgrind_memcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Executable Artifact
        uses: actions/download-artifact@v4
        with:
          name: test_executable
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
      - name: Run Valgrind Memcheck
        run: |
          valgrind --tool=memcheck --leak-check=full --error-exitcode=1 ./lwlog_sandbox