name: Dynamic Analysis

on:
  workflow_run:
    workflows: ["linux"]  # Replace with the exact name of your Linux build workflow
    types: [completed]
  push:
    branches: [ "master", "experimental" ]
  pull_request:
    branches: [ "master", "experimental" ]

jobs:
  valgrind_memcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Executable Artifact
        uses: actions/download-artifact@v3
        with:
          name: test_executable
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
      - name: Run Valgrind Memcheck
        run: |
          valgrind --tool=memcheck --leak-check=full --error-exitcode=1 ./lwlog_sandbox