name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  gcc_build:
    runs-on: ubuntu-latest
    name: GCC Build

    steps:
    - uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install -y gcc g++ 

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure GCC Build
      working-directory: ${{runner.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ $GITHUB_WORKSPACE

    - name: Build with GCC
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

  clang_build:
    runs-on: ubuntu-latest
    name: Clang Build

    steps:
    - uses: actions/checkout@v3

    - name: Install Clang
      run: sudo apt-get install -y clang 

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure Clang Build
      working-directory: ${{runner.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ $GITHUB_WORKSPACE

    - name: Build with Clang
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}