name: macOS

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    name: Apple Clang Build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode (optional)
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Create Build Environment
      run: cmake -E make_directory ${{ runner.workspace }}/build

    - name: Configure CMake
      working-directory: ${{ runner.workspace }}/build
      run: cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build .