name: Windows

on: 
  workflow_dispatch:
  push:
    branches: [ "master", "experimental" ]
  pull_request:
    branches: [ "master", "experimental" ]

env:
  BUILD_TYPE: Release

jobs:
  msvc_build:
    runs-on: windows-latest
    name: MSVC x64 Build
    steps:
      - uses: actions/checkout@v4

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory "${{ runner.workspace }}/build"

      - name: Configure MSVC Build
        shell: bash
        working-directory: "${{ runner.workspace }}/build"
        run: cmake -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "${{ github.workspace }}"

      - name: Build with MSVC
        shell: pwsh
        working-directory: "${{ runner.workspace }}/build"
        run: |
          $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          cmake --build . --config ${{ env.BUILD_TYPE }} --parallel $threads

  mingw_build:
    runs-on: windows-latest
    strategy:
      matrix:
        msys2_env: 
          - { msystem: 'MINGW64', toolchain: 'mingw-w64-x86_64-toolchain', cmake: 'mingw-w64-x86_64-cmake' }
          - { msystem: 'UCRT64', toolchain: 'mingw-w64-ucrt-x86_64-toolchain', cmake: 'mingw-w64-ucrt-x86_64-cmake' }
    name: MinGW x64 ${{ matrix.msys2_env.msystem }} Build
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msys2_env.msystem }}
          update: true
          install: ${{ matrix.msys2_env.toolchain }} ${{ matrix.msys2_env.cmake }}

      - name: Configure MinGW Build
        shell: msys2 {0}
        run: |
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "${{ github.workspace }}"

      - name: Build with MinGW
        shell: msys2 {0}
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

  clang_build:
    runs-on: windows-latest
    name: Clang x64 Build
    steps:
      - uses: actions/checkout@v4

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory "${{ runner.workspace }}/build"

      - name: Configure Clang Build
        shell: bash
        working-directory: "${{ runner.workspace }}/build"
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                "${{ github.workspace }}"

      - name: Build with Clang
        shell: bash
        working-directory: "${{ runner.workspace }}/build"
        run: cmake --build . --config ${{ env.BUILD_TYPE }} --parallel

 intel_build:
    runs-on: windows-latest
    name: Intel x64 Build (VS Integrated)
    steps:
      - uses: actions/checkout@v4

      - name: Install Intel oneAPI Integration via VS Installer
        shell: pwsh
        run: |
          # Define the Visual Studio installation path and installer path.
          $vsInstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise"
          $installerPath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe"
          Write-Host "Modifying Visual Studio installation to add Intel oneAPI integration..."
          & $installerPath modify --installPath $vsInstallPath --add Microsoft.VisualStudio.Component.IntelOneAPIDPCPP

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory "${{ runner.workspace }}/build"

      - name: Configure Intel Build
        shell: bash
        working-directory: "${{ runner.workspace }}/build"
        run: cmake -A x64 -T "Intel" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "${{ github.workspace }}"

      - name: Build with Intel
        shell: pwsh
        working-directory: "${{ runner.workspace }}/build"
        run: |
          $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          cmake --build . --config ${{ env.BUILD_TYPE }} --parallel $threads