name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  msvc_build:
    runs-on: windows-latest
    name: MSVC x64 Build

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure MSVC Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} $GITHUB_WORKSPACE

    - name: Build with MSVC
      working-directory: ${{runner.workspace}}/build
      run: |
        $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
        cmake --build . --config ${{env.BUILD_TYPE}} --parallel $threads

  mingw_build:
    runs-on: windows-latest
    name: MinGW Build
    strategy:
      matrix:
        sys: [mingw64, ucrt64]
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{ matrix.sys }}
        update: true
        install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake

    - name: Configure MinGW Build
      run: |
        echo 'export PATH="$PATH:/usr/bin/mingw64/bin"' >> $GITHUB_ENV
        export PATH="$PATH:/usr/bin/mingw64/bin"
        cmake -B build -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_AR=ar $GITHUB_WORKSPACE
        
    - name: Build with MinGW
      run: cmake --build build
